#!/bin/sh

git filter-branch --env-filter '

am="$GIT_AUTHOR_EMAIL"
cm="$GIT_COMMITTER_EMAIL"

if [ "$GIT_COMMITTER_EMAIL" = "root@debian" ]
then
    cm="vinicius.cscience@gmail.com"
fi
if [ "$GIT_AUTHOR_EMAIL" = "root@debian" ]
then
    am="vinicius.cscience@gmail.com"
fi

export GIT_AUTHOR_EMAIL="$am"
export GIT_COMMITTER_EMAIL="$cm"
'
